baseURL = "https://blog.t98.info/"
publishDir = "docs"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = "homu tec."
theme = "contrast-hugo"

buildDrafts = false
buildFuture = false

enableRobotsTXT = true

enableGitInfo = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10